openshift-install create cluster --dir=$HOME/mycluster

INFO Creating infrastructure resources...
INFO Waiting up to 20m0s for the Kubernetes API at https://api.cluster-2f0b.sand                                                                                                             box916.opentlc.com:6443...
INFO API v1.19.0+e49167a up
INFO Waiting up to 30m0s for bootstrapping to complete...
INFO Destroying the bootstrap resources...
INFO Waiting up to 40m0s for the cluster at https://api.cluster-2f0b.sandbox916.                                                                                                             opentlc.com:6443 to initialize...
INFO Waiting up to 10m0s for the openshift-console route to be created...
INFO Install complete!
INFO To access the cluster as the system:admin user when using 'oc', run 'export                                                                                                              KUBECONFIG=/home/abhishek.s-taashee.com/cluster-2f0b/auth/kubeconfig'
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.cluster-2f0b.sandbox916.opentlc.com/
INFO Login to the console with user: "kubeadmin", and password: "wIaAf-WjpuZ-QbWoP-roxQK"                                                                                                          
INFO Time elapsed: 32m19s
